name: Inflammation CI

#Specify which GitHub events trigger this pipeline
on: push

jobs:
  build:

  # Here we add the matrices definition:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.11", "3.12"]

    # Here we add the reference to the os matrix values
    runs-on: ${{ matrix.os }} 
    
    steps: 
      - name: Checkout repository
        uses: actions/checkout/@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Test with Pytest
        run: |
          python -m pytest --cov=inflammation.models tests/test_models.py